apiVersion: v1
kind: Service
metadata:
  name: pagila-service
  namespace: pagila
spec:
  selector:
    app: pagila-webapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000